### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by CGMossa** [clauswilke/rextendr#2]
For Windows builds, the DLL is named without the "lib"-prefix. 

E.g. in `rust_source`:

```r

  # load shared library
  libfilename <- if (.Platform$OS.type == "windows") {
    paste0(libname, get_dynlib_ext())
  } else {
    paste0("lib", libname, get_dynlib_ext())
  }

  the$shared_lib <- file.path(dir, "target", "debug", libfilename)
  dyn.load(the$shared_lib, local = TRUE, now = TRUE)
```

### Common `CARGO_TARGET_DIR`

A common "trick" to reduce cargo's disk usage, and compile time, is to set [`CARGO_TARGET_DIR`](https://doc.rust-lang.org/cargo/reference/environment-variables.html) or other things, to one common place for all cargo packages. This means that, when `rextendr` tries to locate the `target`, it might not be able to do so properly, as those would be in the common target directory, and not in the project (which is in a temporary location) directory. 

Thus I've added:
```r
  status <- system2(
    command = "cargo",
    args = c(
      "build",
      #"--release",  # release vs debug should be configurable at some point; for now, debug compiles faster
      sprintf("--lib --manifest-path=%s --target-dir %s/target/", file.path(dir, "Cargo.toml"), dir)
    ),
    stdout = stdout,
    stderr = stdout
  )
```
to the `rust_source`.

### `dylib` vs. `cdylib`

While diagnosing my issues, I found this [thread](https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847) describing the difference between `cdylib` and `dylib`. Turned out, it wasn't an issue for me to use `dylib`, but 
this might be a problem down the line.  Also, r-rust/hellorust uses `cdylib`.

### A note: The unlink command does not delete the "loaded" dll, as it is still in use. 
I tried adding a 

```r
clean_build_dir <- function() {
  if (!is.null(the$shared_lib))
    dyn.unload(x = the$shared_lib)
  if (!is.null(the$build_dir)) {
    unlink(the$build_dir, recursive = TRUE, force = TRUE)
    the$build_dir <- NULL
  }
}
```

But this is not good, as it is called after the build is done, and the the R-session is unable to call, since the dll is deleted.

I'll make a PR immediately as I get some comment on these points.

**Comment by clauswilke** [comment]
Thanks for looking into these things. Could I ask you to open separate issues for separate items, so we can knock them off one-by-one? You see the problem arise with your PR, which addresses the first two items but not the next two. So I think we need a new issue for dylib vs cdylib and possibly a new issue for unloading dlls (though I don't think this will be possible; other comparable packages also don't unload).

**Comment by clauswilke** [comment]
Closing this issue as the build-on-windows PR has been merged.
