### ISSUE TITLE
Should this use Rust ABI `dylib` or the C/C++ ABI `cdylib`

### ISSUE THREAD

**Issue by CGMossa** [clauswilke/rextendr#4]
While diagnosing my initial build issues on windows, see #2 , I found this [thread](https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847) describing the difference between `cdylib` and `dylib`. Turned out, it wasn't an issue for me to use `dylib`, but this might be a problem down the line.  Also, r-rust/hellorust uses `cdylib`.

This is specifically concerning the generated `Cargo.toml` file in the `source.R` file.

**Comment by clauswilke** [comment]
What change is needed to switch to `cdylib`? It sounds to me like it's the right thing to do.

**Comment by CGMossa** [comment]
It just requires changing `generate_cargo.toml`. I just don't know what the consequences of that is.
Maybe it entails longer compile time, or some restriction, that I'm unfamiliar with. 
For instance, the hello-code in the `README.md` is 7.1 MB when using `dylib` and 5.5 MB when using `cdylib`. 

Hopefully @dasmoth or Andy have some ideas what this decision entails.

**Comment by clauswilke** [comment]
Tagging @andy-thomason so he sees this issue.

**Comment by andy-thomason** [comment]
It seems that cdylib is intended for building C API extensions for other things that
expect it (such as R) ie. C <-> Rust.

dylib is for extending Rust frameworks and presumably allows rust functions
to call Rust functions Rust <-> Rust.

I would definitely go for cdylib as the C ABI has remained invariant for decades
apart from some minor bug fixes.

**Comment by clauswilke** [comment]
Sounds good, I'll switch to cdylib.

**Comment by clauswilke** [comment]
This is done now.
